name: Post Max Ernst

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: "0 3,7,11,15,19,23 * * *"
jobs:
  post:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: set up environment variables
      run: |
        echo "BSKY_APP_PASSWORD=${{ secrets.MAX_ERNST_APP_PASSWORD }}" >> $GITHUB_ENV
        echo "BSKY_HANDLE=${{ secrets.MAX_ERNST_HANDLE }}" >> $GITHUB_ENV
        echo "JSON_PATH=meta/max-ernst.json" >> $GITHUB_ENV
    - name: install dependencies
      run: pip install atproto wand requests Pillow
    - name: post to bluesky
      run: for i in {1..5}; do python post.py && break || sleep 15; done # retries on fail
